### ISSUE TITLE
Missing alerts_example

### ISSUE THREAD

**Issue by takus** [airbnb/interferon#2]
It seems that https://www.github.com/airbnb/alerts_example is dead link. Can I see examples somewhere else?

**Comment by jonmoter** [comment]
Either a dead link or a private repo.

**Comment by tushar-dadlani** [comment]
Does anyone know if there is any other example that we can take a look at?

**Comment by jimmyngo** [comment]
Created an example repository and updated the link to https://github.com/airbnb/alerts
